name: Claude Code PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, develop ]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: file:./dev.db

    - name: Run Claude Code PR Review
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        DATABASE_URL: file:./dev.db
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
      run: |
        echo "🤖 Claude Code reviewing PR #$PR_NUMBER"
        npx tsx .github/scripts/claude-pr-review.ts

    - name: Commit Claude's suggestions
      if: success()
      run: |
        git config --local user.email "claude@anthropic.com"
        git config --local user.name "Claude Code Bot"

        if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -m "🤖 Claude Code: Auto-fixes from PR review

Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        else
          echo "No changes to commit"
        fi
